[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
material-yew = { version = "0.3.0", features = ["full"] }
reqwasm = "0.5.0"
yew = { version = "0.20", features = ["csr"] }
yew-router = "0.17"
